### ISSUE TITLE
Chrome Autocomplete Triggers pop up

### ISSUE THREAD

**Issue by warmwhisky** [guiassemany/stick-to-me#11]
Hi,

When I use chrome auto fill to fill in shipping or user account it is triggering the pop up. 

Is there any setting or anything I can do to make it only trigger at the top?

Thanks

**Comment by guiassemany** [comment]
Hey, I couldn't reproduce this. Can you recreate this error or record it with a loom?

**Comment by warmwhisky** [comment]
I had to abandon using the package as It popped up continually.

I've still not implemented anything like it yet. when I get time to try again I may try this package again.
