### ISSUE TITLE
Cookie duration

### ISSUE THREAD

**Issue by tswolf** [guiassemany/stick-to-me#4]
Hi there!
I just quickly wanted to ask whether there is a way to set cookie duration once cookies are enabled.

Regards.

**Comment by guiassemany** [comment]
Hi @tswolf!

Its possible. I dont have time to make changes to the code right now, but you should do something like this on line 165.

```js
if (settings.cookie == true) {
 cookiehowm++;
 var expiresAt = new Date().toGMTString(); // just an example. You should put here the date to expire.
 document.cookie="ck_stick_visit="+cookiehowm+";expires='+expiresAt+';path=/";
}
```

Tell me if it helped you!
